#pragma once

//Screen dimensions
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416

//Player constants
#define MARIO_TEXT_POS 4.0f
#define LUIGI_TEXT_POS 0.75f * SCREEN_WIDTH
#define SCORE_HEIGHT 4.0f
#define INITIAL_LIVES 3
#define LIVES_HEIGHT 40.0f
#define INVULNERABILITY_TIME 5.0f
#define INVULN_MULTIPLIER 4.0f
#define LEVEL1_PLAYER_FRAME_DELAY 0.1f
#define LEVEL2_PLAYER_FRAME_DELAY 0.08f
#define MARIO_IDLE_FRAME_COUNT 1
#define MARIO_IDLE_START_FRAME 0
#define MARIO_JUMP_FRAME_COUNT 1
#define MARIO_JUMP_START_FRAME 5
#define MARIO_MOVE_FRAME_COUNT 4
#define MARIO_MOVE_START_FRAME 1
#define MARIO_FRAME_COUNT 6

//Marioland player constants
#define MARIOLAND_INITIAL_LIVES 2
#define MARIOLAND_INIT_POS Vector2D(0.0f, 0.0f)
#define MARIOLAND_JUMP_FORCE 500.0f
#define MARIOLAND_JUMP_DECREMENT 500.0f
#define MARIOLAND_GRAVITY 192.0f
#define MARIOLAND_MOVESPEED 100.0f
#define MARIOLAND_FRAME_COUNT 5
#define MARIOLAND_JUMP_START_FRAME 4
#define MARIOLAND_JUMP_FRAME_COUNT 1
#define MARIOLAND_MOVE_START_FRAME 1
#define MARIOLAND_MOVE_FRAME_COUNT 3
#define MARIOLAND_COLLISION_RADIUS 8.0f
#define MARIOLAND_GOOMBA_SPEED 25.0f
#define MARIOLAND_GOOMBA_FRAME_COUNT 3
#define MARIOLAND_GOOMBA_START_FRAME 0
#define MARIOLAND_GOOMBA_WALK_FRAME_COUNT 2
#define MARIOLAND_GOOMBA_DEAD_FRAME_COUNT 1
#define MARIOLAND_GOOMBA_DEAD_START_FRAME 2
#define MARIOLAND_GOOMBA_DEATH_TIMER 0.5f
#define MARIOLAND_ENEMY_HIT_PLAYER_HEIGHT_PROPORTION 0.6f
#define MARIOLAND_FLY_DEAD_FRAME_COUNT 1
#define MARIOLAND_FLY_DEAD_START_FRAME 2
#define MARIOLAND_FLY_JUMP_TIME 2.0f
#define MARIOLAND_FLY_DEATH_TIMER 3.0f
#define MARIOLAND_FLY_SPEED 60.0f
#define MARIOLAND_FLY_FRAME_COUNT 3
#define MARIOLAND_FLY_START_FRAME 0
#define MARIOLAND_FLY_WALK_FRAME_COUNT 2
#define MARIOLAND_FLY_JUMP_FORCE 400.0f
#define MARIOLAND_FLY_COLLISION_RADIUS 16.0f
#define MARIOLAND_KOOPA_FRAME_COUNT 6
#define MARIOLAND_KOOPA_START_FRAME 0
#define MARIOLAND_KOOPA_WALK_FRAME_COUNT 2
#define MARIOLAND_KOOPA_COLLISION_RADIUS 12.0f
#define MARIOLAND_KOOPA_DEATH_TIME 5.0f
#define MARIOLAND_KOOPA_DEATH_ANIM1_FRAME 2
#define MARIOLAND_KOOPA_DEATH_ANIM2_FRAME 4
#define MARIOLAND_COIN_SPEED 60.0f
#define MARIOLAND_COIN_FRAME_COUNT 1
#define MARIOLAND_COIN_START_FRAME 0
#define MARIOLAND_COIN_ALIVE_TIME 0.5f

//movement constants
#define MOVEMENTSPEED 60.0f
#define GRAVITY 96.0f
#define JUMP_FORCE_DECREMENT 400.0f
#define INITIAL_JUMP_FORCE 400.0f
#define INITIAL_JUMP_FORCE_SMALL 200.0f
#define KOOPA_SPEED 50.0f
#define COIN_SPEED 25.0f
#define GRAVITY_CHECK_FALLOFF 0.1f
#define COLLISION_RADIUS 15.0f

//Map constants
#define MAP_HEIGHT 13
#define MAP_WIDTH 16
#define TILE_WIDTH 32
#define TILE_HEIGHT 32

#define SCREENSHAKE_DURATION 0.25f

//Enemy constants
#define INJURED_TIME 2.5f
#define ENEMY_SPAWN_TIME 10.0f
#define ANIMATION_DELAY 0.25f
#define KOOPA_FRAME_COUNT 5
#define KOOPA_MOVING_FRAME 0
#define KOOPA_MOVING_FRAME_COUNT 4
#define KOOPA_DAMAGED_FRAME 4
#define KOOPA_DAMAGED_FRAME_COUNT 1
#define KOOPA_SCORE 1

//Coin constants
#define COIN_SPAWN_TIME 15.0f
#define COIN_SCORE 2
#define COIN_FRAME_COUNT 5

//Pow block constants
#define POW_COLLISION_INCREASE 0.53125f
#define POW_HITS 3

//Score constants
#define HIGHSCORE_COUNT 5
#define HIGHSCORE_FILE_PATH "highscores.txt"
#define NAME_MAX_LENGTH 10